Repository CrowdStrike/falcon-integration-gateway, pull requests merged in 2025-01, with the labels that each got.

#205 feat: update release run to build and push to gcr.io
  .github/workflows/release.yml
Labels: enhancement, github_actions

#207 fix: fixes issue with loading config when not using package
  Dockerfile
  MANIFEST.in
  fig/config/__init__.py
  setup.py
Labels: bugfixes

#208 chore: bump 3.2.5
  docs/listings/gke/deployer/chart/falcon-integration-gateway/Chart.yaml
  docs/listings/gke/deployer/chart/falcon-integration-gateway/templates/application.yaml
  docs/listings/gke/deployer/schema.yaml
  fig/__init__.py
Labels: release

#209 fix: revert/update existing logic for package files
  fig/config/__init__.py
  setup.py
Labels: bugfixes

#210 chore: bump 3.2.6
  docs/listings/gke/deployer/chart/falcon-integration-gateway/Chart.yaml
  docs/listings/gke/deployer/chart/falcon-integration-gateway/templates/application.yaml
  docs/listings/gke/deployer/schema.yaml
  fig/__init__.py
Labels: release

#211 Update AWS manual docs
  README.md
  docs/aws/manual/README.md
Labels: documentation
